### PR TITLE
Update the npm package contents for field-kit.

### PR DESCRIPTION
**Pull request by eventualbuddha**
This makes a few changes to the package on npm:
- only include dist/ and src/ (plus required files) in the package
- add jsnext:main for build tools that build ES6 (i.e. rollup)
- switch from the lib/ CJS build to the dist/ UMD build for the main
file

### CODE REVIEW

**Comment by iamJoeTaylor** [comment]
<3 it

**Comment by eventualbuddha** [comment]
FYI, this is the list of files that would be included:

```
-rw-r--r--  0 1253   1253     1539 Sep  9 14:19 package/package.json
-rw-r--r--  0 1253   1253     1234 Sep  9 14:12 package/README.md
-rw-r--r--  0 1253   1253    10851 Sep  3 14:01 package/LICENSE
-rw-r--r--  0 1253   1253   227742 Sep  9 14:35 package/dist/field-kit.js
-rw-r--r--  0 1253   1253    92360 Sep  9 14:35 package/dist/field-kit.min.js
-rw-r--r--  0 1253   1253   235873 Sep  9 14:35 package/dist/field-kit.js.map
-rw-r--r--  0 1253   1253   342540 Sep  9 14:35 package/dist/field-kit.min.js.map
-rw-r--r--  0 1253   1253     1818 Sep  3 14:01 package/src/adaptive_card_formatter.js
-rw-r--r--  0 1253   1253     6985 Sep  3 14:01 package/src/delimited_text_formatter.js
-rw-r--r--  0 1253   1253      208 Sep  3 14:01 package/src/dist.js
-rw-r--r--  0 1253   1253      612 Sep  3 14:01 package/src/expiry_date_field.js
-rw-r--r--  0 1253   1253     1398 Sep  3 14:01 package/src/default_card_formatter.js
-rw-r--r--  0 1253   1253     1735 Sep  3 14:01 package/src/formatter.js
-rw-r--r--  0 1253   1253     1745 Sep  3 14:01 package/src/index.js
-rw-r--r--  0 1253   1253    57911 Sep  3 14:01 package/src/number_formatter.js
-rw-r--r--  0 1253   1253     4252 Sep  3 14:01 package/src/number_formatter_settings_formatter.js
-rw-r--r--  0 1253   1253     5235 Sep  3 14:01 package/src/phone_formatter.js
-rw-r--r--  0 1253   1253     1180 Sep  3 14:01 package/src/caret.js
-rw-r--r--  0 1253   1253      901 Sep  3 14:01 package/src/social_security_number_formatter.js
-rw-r--r--  0 1253   1253     2143 Sep  3 14:01 package/src/card_utils.js
-rw-r--r--  0 1253   1253    27035 Sep  3 14:01 package/src/text_field.js
-rw-r--r--  0 1253   1253     3777 Sep  3 14:01 package/src/card_text_field.js
-rw-r--r--  0 1253   1253     4877 Sep  3 14:01 package/src/undo_manager.js
-rw-r--r--  0 1253   1253      406 Sep  3 14:01 package/src/amex_card_formatter.js
-rw-r--r--  0 1253   1253     4540 Sep  3 14:01 package/src/utils.js
-rw-r--r--  0 1253   1253     3857 Sep  3 14:01 package/src/expiry_date_formatter.js
```

**Comment by iamJoeTaylor** [comment]
Going to release this as a patch?

**Comment by eventualbuddha** [comment]
> Going to release this as a patch?

Yeah, seems reasonable since there is no API change.

**Comment by eventualbuddha** [comment]
Released in v2.0.1.

**Comment by alexgorbatchev** [comment]
Should the `lib` folder be completely removed then?

**Comment by eventualbuddha** [comment]
Yeah. I did that in #30 but it could easily be a separate PR.

**Pull request merged**
